### ISSUE TITLE
Enhancement request: Diff sizes of each http request

### ISSUE THREAD

**Issue by tufandevrim** [sitespeedio/compare#62]
Have separate section (table) compares every https request side by side with diff size + and - to determine what actually increased or decreased the payload.

**Comment by tufandevrim** [comment]
This would make our life so much easier. Thanks @soulgalore and please let me know when we can get this in.

**Comment by soulgalore** [comment]
@tufandevrim let me check if I understand the use case: Check all responses between two runs, if the URL is the same AND the size is different, highlight that URL?

**Comment by soulgalore** [comment]
Ping @tufandevrim again, sorry I just want to check that I match your use case, I'm gonna push this the coming days. 

It will work like this: 
You will have two lists in the console: one with requests that is only in page 1 and the a list with what's only in page 2 (and each size). 

Because you change URL right when there's a changed in a an assets (so you can have long cache times)? Or is there a use case comparing the exact same URL with a different size?

**Comment by tufandevrim** [comment]
Hi @soulgalore 

Following screenshot summarizes what I am looking for:

![screen shot 2018-11-26 at 2 31 43 pm](https://user-images.githubusercontent.com/1676189/49046168-1251d800-f188-11e8-89a3-fc897b8ecee7.png)

I like both tables showing under the compare report (https://raw.githubusercontent.com/sitespeedio/compare/master/docs/img/compare.png) if possible

This will help us to figure out what actually caused the increase or decrease in total payload and pinpoints the actual asset.

Here is the gdoc link so we can discuss the requirement in the doc as well
https://docs.google.com/spreadsheets/d/1D0fHoy9dtDeYEk3yeLkKxY6slAIeroQypF0zX873KVI/edit?usp=sharing

**Comment by soulgalore** [comment]
Hi @tufandevrim thanks for taking the time to explain. 

I made a quick POC in #63  - do you have time to test it + fine-tune (the HTML needs some more love and we need to discuss how display the URL). I tries with a couple of Wikipedia URLs and it seems to work ok.

**Comment by soulgalore** [comment]
This is what it looks like at the moment: 
<img width="1412" alt="screen shot 2018-11-27 at 20 46 22" src="https://user-images.githubusercontent.com/540757/49107322-ace41100-f285-11e8-9f7c-c1bb84b86455.png">

**Comment by tufandevrim** [comment]
Looks great. Here are some feedbacks
1. Ellipsis in the middle of the url would be super helpful since we need to see domain name at the beginning and extension at the end
2. Diff `kb` is preferred, it should be okay to show`Not Changed` even if there is a byte change but no kb change. We may even make this configurable (compare results in kb or byte etc...)
3. Got into this PR and compared `https://en.wikipedia.org/wiki/Main_Page`'s har, got weird result. see below
![screen shot 2018-11-27 at 2 01 05 pm](https://user-images.githubusercontent.com/1676189/49114384-ed736880-f24c-11e8-914c-b55fb3b9ae5f.png)
Here is the har https://gist.github.com/tufandevrim/4709ccfdc2e37c9e7c1c5acb4720e1d5#file-browsertime-har

4. Love the see Har1 and Har2 totals at the bottom if the table as I requested above
5. Love the see labels as `X kb increased` in red, `X kb decreased` in green, `Removed` in green`, `New` in red`, `Not changed` as black or gray :) 
6. Love the see second table as well
![screen shot 2018-11-27 at 2 08 03 pm](https://user-images.githubusercontent.com/1676189/49114788-ea2cac80-f24d-11e8-9358-9fbf858de169.png)

Let me know if you need help, I can help.

**Comment by soulgalore** [comment]
> Ellipsis in the middle of the url would be super helpful since we need to see domain name at the beginning and extension at the end

Yeah, it's there but not for URL longer than X. I think we can do something like WPT:
<img width="249" alt="screen shot 2018-11-28 at 7 05 49 am" src="https://user-images.githubusercontent.com/540757/49132301-168f0a00-f2dc-11e8-9c1b-d585c222f405.png">

> Diff kb is preferred, 

You are right. Right now the limit is hardcoded. Lets change to KB and make the limit a smart limit.

> Love the see labels as green/red

Yeah but is an increased size always bad? I mean it could be some pretty awesome functionality that's been added :) This is lower prio for me but if you feel strong for it, please do a PR :)

> Sortable Diff column would be super helpful as well.

True, we should have that!

> Love the see Har1 and Har2 totals at the bottom of the table

Yep.

> Love the see second table as well

Lets do that as a second step when the first is working as it should.

> Got into this PR and compared https://en.wikipedia.org/wiki/Main_Page's har, got weird result. see below

It's different URLs because it's different parameter. This can be hard to see when we shorten the URL.


I'll do as much as I can during today and then we can check what you can do.

Best
Peter

**Comment by soulgalore** [comment]
I've pushed a couple of changes. IMHO this is ready to go and then we can do some follow PRs:

> Ellipsis in the middle of the url would

I've followed the same pattern as WPT. It looks good.

> Diff kb is preferred, it should be okay to showNot Changed even if there is a byte change but no kb change. We may even make this configurable (compare results in kb or byte etc...)

Added diff in kb. There one thing here: We don't show responsen with a change smaller than 1000 bytes. When I tested in Chrome it seems like the calculation isn't 100% the same from time to time. So at the moment we do not show "Not changed".

> Love the see labels as X kb increased in red, X kb decreased in green, Removed in green, New in red, Not changed as black or gray :)

Fixed the colors, and added +- in front off changes.

> Sortable Diff column would be super helpful as well.

This can come in a new PR later on.

> Love the see Har1 and Har2 totals at the bottom of the table

Done.

> Love the see second table as well

Done.


If you have the time, add sorting (in sitespeed.io we use https://github.com/sitespeedio/sitespeed.io/blob/master/lib/plugins/html/assets/js/sortable.min.js but I guess there can be a better way of doing it now since that is old). But lets do that after we merged this, then there's no hurry.

<img width="1405" alt="screen shot 2018-11-28 at 08 50 34" src="https://user-images.githubusercontent.com/540757/49136693-b81d5800-f2ea-11e8-9cc2-03da5d1e22a2.png">
<img width="1400" alt="screen shot 2018-11-28 at 08 50 26" src="https://user-images.githubusercontent.com/540757/49136694-b81d5800-f2ea-11e8-808e-6a4e1b8b9141.png">



Best
Peter

**Comment by tufandevrim** [comment]
Awesome. You rock @soulgalore. Cant wait to use this. We can handle sort later

**Comment by soulgalore** [comment]
released

**Comment by monsuj** [comment]
hi @soulgalore ,

Wonderful work Done!! 

But is this feature disabled right now. When I am comparing in https://compare.sitespeed.io/ I am not seeing this feature am i missing something.
